### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by scuba323** [specktator/jabber-registration-tool#1]
Checking password: Password OK

Unknown error, error code = '0'.

Just got done doing the DNS SRV records, and the dig is correct

**Comment by scuba323** [comment]
[Apache Log if that helps...](http://paste.scuba323.com/view/4673b37f)

**Comment by specktator** [comment]
@scuba323 Sorry for the late response. Paste index.php and register.php .
I think there's something wrong in your post requests.

**Comment by scuba323** [comment]
I enableded ejabberds web_register module. Thanks anyways :sunglasses:
